djangoajaxcrud/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('enroll/',include('enroll.urls')),

]

enroll/urls.py
from django.urls import path
from . import views

app_name="enroll"
urlpatterns=[
	path('',views.home,name='home'),
	path('save/',views.save_data,name='save'),
	path('delete/',views.delete_data,name='delete'),
	path('edit/',views.edit_data,name='edit'),
]

enroll/models.py
from django.db import models

# Create your models here.
class User(models.Model):
	name=models.CharField(max_length=70)
	email=models.EmailField(max_length=100)
	password=models.CharField(max_length=100)

enroll/forms.py
from django import forms

from .models import User

class StudentRegistration(forms.ModelForm):
	class Meta:
		model=User
		fields='__all__'
		widgets={
			'name':forms.TextInput(attrs={'class':'form-control','id':'nameid'}),
			'email':forms.EmailInput(attrs={'class':'form-control','id':'emailid'}),
			'password':forms.PasswordInput(attrs={'class':'form-control','id':'passwordid'})
		}

enroll/views.py
from django.http.response import JsonResponse
from django.shortcuts import render
from django.http import HttpResponse
from .forms import StudentRegistration
from .models import User
# from django.views.decorators.csrf import csrf_exempt
# Create your views here.
def home(request):
	form=StudentRegistration()
	stud=User.objects.all()
	
	return render(request,'enroll/home.html',{'form':form,'stud':stud})
# @csrf_exempt
def save_data(request):
	if request.method=='POST':
		form=StudentRegistration(request.POST)
		if form.is_valid():
			name=request.POST['name']
			email=request.POST['email']
			password=request.POST['password']
			sid=request.POST.get('stuid')


			if sid=='':
				user=User(name=name,email=email,password=password)
			else:
				user=User(id=sid,name=name,email=email,password=password)
			user.save()

			stud=User.objects.values()
			student_data=list(stud)
			return JsonResponse({"status":'Save' , 'student_data':student_data})
		else:
			return JsonResponse({'status':0})

def delete_data(request):
	if request.method=='POST':
		id=request.POST.get('sid')
		pi=User.objects.get(pk=id)
		pi.delete()
		return JsonResponse({'status':1})
	else:
		return JsonResponse({'status':0})

def edit_data(request):
	if request.method=='POST':
		id=request.POST.get('sid')
		student=User.objects.get(pk=id)
		student_data={
			"id":student.id,
			"name":student.name,
			"email":student.email,
			"password":student.password,
		}
		return JsonResponse(student_data)

enroll/templates/enroll/ajax.html
<script>
    $('#btnsave').click(function() {
        console.log("Save button clicked");
        output = "";
        let sid = $("#stuid").val();
        let nm = $("#nameid").val();
        let em = $("#emailid").val();
        let pw = $("#passwordid").val();
        let csr = $("input[name=csrfmiddlewaretoken]").val();

        if (nm == "") {
            console.error("Please enter name");
        } else if (em == "") {
            console.error("Please enter email");
        } else if (pw == "") {
            console.error("Please enter password");
        } else {
            // console.log(nm);
            // console.log(em);
            // console.log(pw);

            mydata = {
                stuid: sid,
                name: nm,
                email: em,
                password: pw,
                csrfmiddlewaretoken: csr,
            };

            $.ajax({
                url: "{% url 'enroll:save' %}",
                method: "POST",
                data: mydata,
                success: function(data) {
                    // console.log(data);
                    x = data.student_data;
                    if (data.status == "Save") {
                        console.log("Form Submitted Successfully");
                        // console.log(data.student_data)
                        for (i = 0; i < x.length; i++) {
                            output += "<tr><td>" + x[i].id + "</td>";
                            output += "<td>" + x[i].name + "</td>";
                            output += "<td>" + x[i].email + "</td>";
                            output += "<td>" + x[i].password + "</td>";


                            output += ` <td><input type='button' data-sid=${x[i].id} id="btn-edit" class='btn btn-warning btn-sm' value='Edit'></td>`;
                            output += ` <td><input type='button' data-sid=${x[i].id} id="btn-del" class='btn btn-danger btn-sm' value='Delete'></td></tr>`;
                        }
                        $("#tbody").html(output);
                        $("#stuid").val('');
                        $("form")[0].reset();

                    } else if (data.status == 0) {
                        console.log("Unable to Save Form");
                        $("#stuid").val('');
                        $("form")[0].reset();
                    }

                },

            });
        }
    });


    //delete data

    $("#tbody").on('click', '#btn-del', function() {
        console.log("delete clicked");
        let id = $(this).attr("data-sid");
        let csr = $("input[name=csrfmiddlewaretoken]").val();

        console.log(id);
        mydata = {
            sid: id,
            csrfmiddlewaretoken: csr,

        }
        mythis = this;
        $.ajax({
            url: "{%url 'enroll:delete' %}",
            method: "POST",
            data: mydata,

            success: function(data) {
                // console.log(data);
                if (data.status == 1) {
                    console.log("data deleted successfully");
                    $(mythis).closest("tr").fadeOut();
                } else if (data.status == 0) {
                    console.error("Unable to delete data");
                }
            }
        })
    })


    //Edit data

    $("#tbody").on('click', '#btn-edit', function() {
        console.log("delete clicked");
        let id = $(this).attr("data-sid");
        let csr = $("input[name=csrfmiddlewaretoken]").val();

        console.log(id);
        mydata = {
            sid: id,
            csrfmiddlewaretoken: csr,

        }
        $.ajax({
            url: "{%url 'enroll:edit' %}",
            method: "POST",
            data: mydata,

            success: function(data) {
                // console.log(data);
                $("#stuid").val(data.id);
                $("#nameid").val(data.name);
                $("#emailid").val(data.email);
                $("#passwordid").val(data.password);
            }
        })
    })
</script>

enroll/templates/enroll/home.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Registration</title>
    <link rel="stylesheet" href="{% static 'enroll/css/bootstrap.css' %}">

</head>

<body>

    <div class="container mt-5">
        <h2 class="text-center alert alert-danger">
            Django Ajax Project
        </h2>
        <div class="row">
            <div class="col-sm-4">
                <h4 class="text-center alert alert-info">Add/Update Student</h4>
                <form action="" method="post">

                    {%csrf_token%}
                    <input type="hidden" name="stuid" id="stuid" /> {{form.as_p}}

                    <input type="button" id="btnsave" class="btn btn-success" value="Save">
                </form>
            </div>
            <div class="col-sm-7">
                <h4 class="text-center alert alert-info">Show Student Information</h4>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                            <th scope="col">Password</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody id="tbody">
                        {% for stu in stud%}
                        <tr>
                            <td>{{stu.id}}</td>
                            <td>{{stu.name}}</td>
                            <td>{{stu.email}}</td>
                            <td>{{stu.password}}</td>
                            <td><input type="button" data-sid="{{stu.id}}" id="btn-edit" class="btn btn-warning btn-sm" value="Edit"></td>
                            <td><input type="button" data-sid="{{stu.id}}" id="btn-del" class="btn btn-danger btn-sm" value="Delete"></td>
                        </tr>
                        {%endfor%}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script src="{% static 'enroll/js/jquery.js' %}"></script>
    <script src="{% static 'enroll/js/popper.js' %}"></script>
    <script src="{% static 'enroll/js/bootstrap.js' %}"></script>

    {%include "enroll/ajax.html" %}
</body>

</html>